Documentation
mum-rs/mum pull request #61
Opened 2021-01-13 22:19 UTC by sornas

2021-06-13 09:39 UTC, sornas commented
Honestly, we should merge these now and work on one part at a time. I'll update to match #102 and then mark as ready.

2021-06-13 17:04 UTC, default-username-852 requested changes
Great job in general! It might be nice to add some module level documentation to mumlib as well, and maybe add a `#![warn(missind_docs)]`, if the aim of this PR is to document all of mumlib.

2021-06-13 17:04 UTC, default-username-852 commented on mumlib/src/state.rs
>  pub struct Channel {
Document this struct and the Server struct.

2021-06-13 17:04 UTC, default-username-852 commented on mumlib/src/state.rs
> +    pub fn new(
Document this function.

2021-06-13 17:04 UTC, default-username-852 commented on mumlib/src/state.rs
> +    /// Create an iterator over this channel and its children in a pre-order
What is a pre-order traversal?

2021-06-15 10:49 UTC, sornas commented
> and maybe add a `#![warn(missind_docs)]`

Still 85 missing documentations in mumlib, so no. Not yet.

2021-06-19 15:55 UTC, default-username-852 approved these changes
Looks good!

2021-06-19 16:39 UTC, merged